### ISSUE TITLE
root_node.state contains solution,  is it reasonable？

### ISSUE THREAD

**Issue by fenngMing** [SimpleBerry/LLaMA-O1#11]
first, **initial_state**=self.envoirment.sample_initial_state()  #here returns both initial state and solution
then **root_node** = TreeNode(state=initial_state) #here root_node contans solution too
third **path_to_string**  here solution leaks to prompt
f"<start_of_father_id>{node.parent.index if node.parent else -1}<end_of_father_id><start_of_local_id>{node.index}<end_of_local_id><start_of_thought>{**node.state**}<end_of_thought><start_of_rating>{value_to_rating_token(node.value)}<end_of_rating>"
            for node in path[::-1]

**Comment by trotsky1997** [comment]
Will be fix in next commit

**Comment by trotsky1997** [comment]
initial_state, gt=self.envoirment.sample_initial_state() 
 
 return of `sample_initial_state` has been changed, but I have forget to change corresponding call, sorry
