### ISSUE TITLE
error for log_probs[:, 0].item()

### ISSUE THREAD

**Issue by Megasister** [SimpleBerry/LLaMA-O1#12]
log_probs[:, 0].item() *** 
RuntimeError: a Tensor with 128256 elements cannot be converted to Scalar

log_probs[:, 0].shape: gaves result of torch.Size([1, 1, 128256])

**Comment by trotsky1997** [comment]
这个函数对于llama3估计要重写

就是获得倒数第二个hidden上表达正向评分预测token的logit就行

按照这个逻辑重写就行

**Comment by TraceIvan** [comment]
> 这个函数对于llama3估计要重写
> 
> 就是获得倒数第二个hidden上表达正向评分预测token的logit就行
> 
> 按照这个逻辑重写就行

@trotsky1997 Hello. I'm wondering specifically if it means using the output predicted logits of the special token '<start_of_rating>' in the input (i.e., `model(**inputs, return_dict=True).logits[:, -2, :]`) to predict the next token (either '<positive_rating>' or '<negative_rating>')？

Besides, I noticed that the special token "<positive_rating>" was added to the end of the input text. Why do this operation? After all, the output logits of "<positive_rating>" are not utilized.
```
text_for_value = value_head_template(node) + '<positive_rating>'
```
