### ISSUE TITLE
About LLaMA-Berry

### ISSUE THREAD

**Issue by TexasRangers86** [SimpleBerry/LLaMA-O1#13]
Does this project follow 'LLaMA-Berry: Pairwise Optimization for O1-like Olympiad-Level Mathematical Reasoning' ?
The implementation method in this project is different from the mentioned paper. 
I'm confused whether this project follows LLaMA-Berry, or they are independently works.
Looking forward to your reply！

**Comment by trotsky1997** [comment]
This is a new project with highly experimental.

**Comment by TexasRangers86** [comment]
Got it.
Thanks a lot！
