### ISSUE TITLE
Using other models will result in an error

### ISSUE THREAD

**Issue by MRQJsfhf** [SimpleBerry/LLaMA-O1#14]
**This error will occur when using several different models:**
RuntimeError                              Traceback (most recent call last)
Cell In[20], line 1129
   1126 num_iterations = 1
 
-> 1129 trainer.train(num_iterations=num_iterations)
   1130 model.save_pretrained('./output')

Cell In[20], line 928, in RLSPTrainer.train(self, num_iterations, beta_start, beta_frames, **kwargs)
    926 # Self-play to collect new experiences
    927 initial_state = self.envoirment.sample_initial_state()
--> 928 root_node = self.self_play(initial_state)
    929 self.collect_experience(root_node)
    931 # Anneal beta over time to 1.0

Cell In[20], line 797, in RLSPTrainer.self_play(self, initial_state)
    795 """Perform self-play to generate experiences."""
    796 root_node = TreeNode(state=initial_state)
--> 797 root_node = self.mcts.search(root_node)
    798 return root_node

Cell In[20], line 274, in MCTS.search(self, root_node)
    271     root_node.value = 0
    273 for _ in tqdm(range(self.num_simulations)):
--> 274     self.simulate(root_node)
    275     max_reward, path_len = find_max_reward_path(root_node)
    276     print(f'find max reward path: {max_reward} with {path_len} steps.')

Cell In[20], line 292, in MCTS.simulate(self, node)
    290 def simulate(self, node):
    291     if node.is_leaf() or node.should_expand():
--> 292         value = self.expand_node(node) * self.discount_factor
    293     else:
    294         best_child = self.select_action(node)

Cell In[20], line 312, in MCTS.expand_node(self, node)
    310 node.policy_varentropy[child_node] = varentropy
    311 node.add_child(child_node)
--> 312 child_node.value = self.compute_value(child_node)
    313 child_node.meta = meta
    314 # if child_node.meta == "<conclusion>":

Cell In[20], line 328, in MCTS.compute_value(self, node)
    326 def compute_value(self, node):
    327     # Use the model to predict the value of the current state
--> 328     value = compute_value_head(self.model, self.tokenizer, node)
    329     node.value = value
    330     node.original_value = copy.deepcopy(value)

File /usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

Cell In[20], line 545, in compute_value_head(model, tokenizer, node)
    542 value_logits = torch.stack([positive_logit, negative_logit], dim=1)
    544 probs, log_probs = robust_softmax(value_logits)
--> 545 return log_probs[:, 0].item()

RuntimeError: a Tensor with 151936 elements cannot be converted to Scalar

**Comment by trotsky1997** [comment]
https://github.com/SimpleBerry/LLaMA-O1/issues/12
