### ISSUE TITLE
Is there any comparison between SR-MCTS rm@1 results and baseline models?

### ISSUE THREAD

**Issue by solitaryzero** [SimpleBerry/LLaMA-O1#18]
As I understand it, rm@8 basically means sorting the samples according to reward values, and once any of the top-8 samples is correct, then the whole data point is considered to be correct.
In this way, rm@8 results should be compared with **pass@8** results of the baseline LLMs.

But the baseline results in the paper seems to be simple **pass@1** (greedy) results, which is unfair to compare against rm@8.
Is there any comparison between rm@1 SR-MCTS results and baseline pass@1 results?
Or as a substitute, is there any comparison between rm@8 SR-MCTS results and baseline pass@8 results?

**Comment by w-yibo** [comment]
I have the same question.
