### ISSUE TITLE
Issue for training

### ISSUE THREAD

**Issue by MaxLuo233** [SimpleBerry/LLaMA-O1#19]
Since I got torch.cuda out-of-memory error during training with a 7B model on 4×A6000 (each with 49860MB GPU memory), I wonder How to compute GPU memory consumed during SR-MCTS training process? Is it different from traditional computing method of GPU memory consumed in training process?

**Comment by trotsky1997** [comment]
https://github.com/SimpleBerry/LLaMA-O1/issues/13#issuecomment-2470436745
