### ISSUE TITLE
qwen error

### ISSUE THREAD

**Issue by jiangix-paper** [SimpleBerry/LLaMA-O1#3]
Thanks for your great work. I use the model qwen2.5-1.5B-instruct to replace gemma-2B, but it has the error :

return log_probs[:, 0].item()
           ^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: a Tensor with 151936 elements cannot be converted to Scalar

**Comment by jiangix-paper** [comment]
![image](https://github.com/user-attachments/assets/5171b41a-c939-4ec9-bf79-4220b702ca6c)

**Comment by trotsky1997** [comment]
Can you try print the shape of tensor before line 545?

**Comment by ljch2018** [comment]
Same error! when tested on Llama3.1 model.

**Comment by trotsky1997** [comment]
Changed heads to instruction-following fashion, enable models without special tokens to be used in data collection.

**Comment by trotsky1997** [comment]
> Same error! when tested on Llama3.1 model.

offline data collection now may work with non-gemma models, you can have a test
