### ISSUE TITLE
added_tokens not in other models (e.g LLama3.1), which may cause error.

### ISSUE THREAD

**Issue by ljch2018** [SimpleBerry/LLaMA-O1#6]
https://huggingface.co/qq8933/OpenLongCoT-Base-Gemma2-2B/blob/main/added_tokens.json
`
{
--
  | "<conclusion>": 256006,
  | "<critic>": 256005,
  | "<end_of_father_id>": 256012,
  | "<end_of_local_id>": 256014,
  | "<end_of_rating>": 256002,
  | "<end_of_thought>": 256008,
  | "<negative_rating>": 256004,
  | "<positive_rating>": 256003,
  | "<problem>": 256009,
  | "<refine>": 256010,
  | "<start_of_father_id>": 256011,
  | "<start_of_local_id>": 256013,
  | "<start_of_rating>": 256000,
  | "<start_of_thought>": 256007,
  | "<unknown_rating>": 256001
  | }

`

**Comment by trotsky1997** [comment]
| "": 256009,
  | "": 256010,
  
  
    | "": 256006,
  | "": 256005,
  
  delete these lines

**Comment by trotsky1997** [comment]
Changed heads to instruction-following fashion, enable models without special tokens to be used in data collection.

**Comment by trotsky1997** [comment]
Fixed in the latest offline scripts
