### ISSUE TITLE
Not clear on get_max_node_id_in_tree

### ISSUE THREAD

**Issue by SwamiKannan** [SimpleBerry/LLaMA-O1#7]
in online_train.py Line 91
```
def get_max_node_id_in_tree(node):
          if not node.parent:
                  while node.parent:
                      node = node.parent
```
The first two lines contradict each other. If there is a node.parent, this loop will not execute. If there is no node.parent, the while loop will exit immediately. 

Am I missing something ?

**Comment by trotsky1997** [comment]
You're right, it's my fault, you're welcome to open a pull request

**Comment by SwamiKannan** [comment]
I think you already resolved it !

**Comment by SwamiKannan** [comment]
Done... https://github.com/SimpleBerry/LLaMA-O1/pull/8. thanks !

**Comment by SwamiKannan** [comment]
I had updated a comment saying it was already updated in your repo but that was my mistake for comparing wrong repos during PR creation. Thanks

**Comment by trotsky1997** [comment]
Great Works!
